CREATE TABLE users (
  id INT NOT NULL AUTO_INCREMENT,
  username VARCHAR(10) NOT NULL,
  password VARCHAR(512) NOT NULL,
  email VARCHAR(256) NOT NULL,
  salt VARCHAR(256) NOT NULL
);

ALTER TABLE users ADD CONSTRAINT users_pk PRIMARY KEY (id);
ALTER TABLE users ADD CONSTRAINT users_uq UNIQUE (username);